# syntax=docker/dockerfile:1

ARG BASE_IMAGE=dst-distribution:latest
FROM ${BASE_IMAGE}

ARG RUNTIME_ASSETS_DIGEST=unknown
LABEL org.dst-distribution.assets-digest="${RUNTIME_ASSETS_DIGEST}"

# 仅刷新运行时配置，不执行 SteamCMD。
COPY --chown=dst:dst preset /opt/dst-preset
COPY --chown=dst:dst config-templates /opt/dst-config-templates
COPY scripts/start-dst /usr/local/bin/start-dst
COPY scripts/merge-modoverrides.lua /usr/local/bin/merge-modoverrides.lua

USER root
RUN chmod +x \
      /usr/local/bin/start-dst \
      /usr/local/bin/merge-modoverrides.lua
USER dst
